#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

validate_bootentries_section() {
	uci_load_validate bootentries bootentries "$1" "$2" \
		'boot_partition:string' \
		'boot_path:string:/' \
		'ibft:bool:0' \
		'cmdline_default:string' \
		'cmdline_iscsi:string' \
		'cmdline_remove:string' \
		'menu_title:string:OpenWrt PXE Boot Menu' \
		'menu_username:string' \
		'menu_password:string'
}

bootentries_config() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	sleep 10	# Wait for DHCP allocation. TODO: Replace with service retry
	. /lib/functions/network.sh
	network_flush_cache
	network_get_ipaddr lan_addr "lan"
	if [ -z "${lan_addr}" ]; then
		echo "LAN IP address not yet set, not generating /srv/pxe/ configuration"
		return 1
	fi

	cat > /srv/pxe/tftp/ipxe/entry.ipxe <<EOF
#!ipxe
  
login
set target-server-ip $lan_addr
set boot-url http://\${username:uristring}:\${password:uristring}@\${target-server-ip}:81/
chain \${boot-url}cgi-bin/get-menu-ipxe
EOF

	rm -rf /srv/pxe/bootentries
	mkdir /srv/pxe/bootentries

	cat > /tmp/partial.ipxe.header.tmp <<EOF
#!ipxe

EOF

	cat > /tmp/partial.ipxe.menu.tmp <<EOF

:start
menu $menu_title
item --gap --             ------------------------- Operating systems ------------------------------
EOF

	cat > /tmp/partial.ipxe.contents.tmp <<EOF
item --gap --             ------------------------- Advanced options -------------------------------
item config               Configure settings
item shell                Drop to iPXE shell
item reboot               Reboot computer
item
item exit                 Exit iPXE and continue BIOS boot
choose selected || goto shell
goto \${selected}

:shell
echo Type 'exit' to get the back to the menu
shell
goto start

:failed
echo Booting failed, dropping to shell
goto shell

:reboot
reboot

:exit
exit

:config
config
goto start

# Boot entries
EOF

	umount -f /mnt || true
	mount -o ro "$boot_partition" /mnt || echo "Error: Unable to mount boot partition: $boot_partition"

	entries_found="0"
	if [ -d "/mnt/$boot_path/loader/entries" ]; then
		echo "Searching for BootLoaderSpec files in /mnt/$boot_path/loader/entries ..."
		# Create an menu entry for every BootLoaderSpec file
		for entry in "/mnt/$boot_path/loader/entries"/*.conf; do
			TITLE="$(sed -n 's/^title[ \t]*\(.*\)/\1/p' $entry)"
			KERNEL_PATH="$(sed -n 's/^linux[ \t]*\(.*\)/\1/p' $entry)"
			INITRD_PATH="$(sed -n 's/^initrd[ \t]*\(.*\)/\1/p' $entry)"
			OPTIONS="$(sed -n 's/^options[ \t]*\(.*\)/\1/p' $entry | sed 's/ quiet//g')"
			if [ -n "$TITLE" -a -n "$KERNEL_PATH" -a -n "$INITRD_PATH" ]; then
				LABEL="$(basename "$entry")"
				mkdir -p "/srv/pxe/bootentries/$LABEL"
				KERNEL_FILE="$(basename "$KERNEL_PATH")"
				INITRD_FILE="$(basename "$INITRD_PATH")"
				KERNEL_IMG="bootentries/$LABEL/$KERNEL_FILE"
				INITRD_IMG="bootentries/$LABEL/$INITRD_FILE"
				cp "/mnt/$boot_path/$KERNEL_PATH" "/srv/pxe/$KERNEL_IMG"
				cp "/mnt/$boot_path/$INITRD_PATH" "/srv/pxe/$INITRD_IMG"
				chmod 644 "/srv/pxe/$KERNEL_IMG"
				chmod 644 "/srv/pxe/$INITRD_IMG"
				echo -e "item $LABEL $TITLE" >> /tmp/partial.ipxe.menu.tmp
		
				echo -e "" >> /tmp/partial.ipxe.contents.tmp
				echo -e ":$LABEL" >> /tmp/partial.ipxe.contents.tmp
				echo -e "kernel \${boot-url}$KERNEL_IMG" >> /tmp/partial.ipxe.contents.tmp
				echo -e "initrd \${boot-url}$INITRD_IMG" >> /tmp/partial.ipxe.contents.tmp
				echo -e "imgargs $KERNEL_FILE initrd=$INITRD_FILE $OPTIONS $cmdline_iscsi" >> /tmp/partial.ipxe.contents.tmp
				echo -e "boot || goto failed">> /tmp/partial.ipxe.contents.tmp
				echo -e "goto start" >> /tmp/partial.ipxe.contents.tmp
				entries_found="$((entries_found+1))"
			fi
		done
	else
		echo "Searching for kernels in /mnt/$boot_path ..."
		for KERNEL_FILE in $(ls -t "/mnt/$boot_path" | grep 'vmlinuz-.*' | grep -v ".hmac$"); do
			KERNEL_VERSION="$(echo $KERNEL_FILE | sed 's/vmlinuz-//g')"
			# Find matching Initramfs image
			if [ -f "/mnt/$boot_path/initramfs-$KERNEL_VERSION.img" ]; then
				INITRD_FILE="initramfs-$KERNEL_VERSION.img"
			elif [ -f "/mnt/$boot_path/initrd.img-$KERNEL_VERSION" ]; then
				INITRD_FILE="initrd.img-$KERNEL_VERSION"
			else
				echo "Warning: could not find any initramfs image for PXE TFTP boot matching kernel $KERNEL_FILE, skipping..."
				continue
			fi
			LABEL="$KERNEL_FILE"
			mkdir -p "/srv/pxe/bootentries/$LABEL"
			KERNEL_IMG="bootentries/$LABEL/$KERNEL_FILE"
			INITRD_IMG="bootentries/$LABEL/$INITRD_FILE"
			cp "/mnt/$boot_path/$KERNEL_FILE" "/srv/pxe/$KERNEL_IMG"
			cp "/mnt/$boot_path/$INITRD_FILE" "/srv/pxe/$INITRD_IMG"
			chmod 644 "/srv/pxe/$KERNEL_IMG"
			chmod 644 "/srv/pxe/$INITRD_IMG"
			echo -e "item $LABEL $LABEL" >> /tmp/partial.ipxe.menu.tmp
	
			echo -e "" >> /tmp/partial.ipxe.contents.tmp
			echo -e ":$LABEL" >> /tmp/partial.ipxe.contents.tmp
			echo -e "kernel \${boot-url}$KERNEL_IMG" >> /tmp/partial.ipxe.contents.tmp
			echo -e "initrd \${boot-url}$INITRD_IMG" >> /tmp/partial.ipxe.contents.tmp
			echo -e "imgargs $KERNEL_FILE initrd=$INITRD_FILE $cmdline_default $cmdline_iscsi" >> /tmp/partial.ipxe.contents.tmp
			echo -e "boot || goto failed">> /tmp/partial.ipxe.contents.tmp
			echo -e "goto start" >> /tmp/partial.ipxe.contents.tmp
			entries_found="$((entries_found+1))"
		done
	fi
	umount /mnt

	if [ "$ibft" = "1" ]; then
		echo -e "set initiator-iqn $(uci get tgt.1.allow_name)" >> /tmp/partial.ipxe.header.tmp
		echo -e "set username $(uci get tgt.user_in.user)" >> /tmp/partial.ipxe.header.tmp
		echo -e "set password $(uci get tgt.user_in.password)" >> /tmp/partial.ipxe.header.tmp
		echo -e "set reverse-username $(uci get tgt.user_out.user)" >> /tmp/partial.ipxe.header.tmp
		echo -e "set reverse-password $(uci get tgt.user_out.password)" >> /tmp/partial.ipxe.header.tmp

		lun_idx=0
		drive_idx="$(printf "%i" "0x80")"
		while uci get tgt.@lun[$lun_idx] &> /dev/null ; do
			lun_idx=$((lun_idx+1));
			target_uri="iscsi:\${target-server-ip}:::$lun_idx:$(uci get tgt.1.name)"
			drive="$(printf "%x" "$drive_idx")"
			drive_idx=$((drive_idx+1));
			echo "sanhook --drive 0x$drive $target_uri" >> /tmp/partial.ipxe.header.tmp
		done

		echo -e "item sanboot iBFT SAN boot" >> /tmp/partial.ipxe.menu.tmp
		echo -e "" >> /tmp/partial.ipxe.contents.tmp
		echo -e ":sanboot" >> /tmp/partial.ipxe.contents.tmp
		echo -e "sanboot || goto failed" >> /tmp/partial.ipxe.contents.tmp
		echo -e "goto start" >> /tmp/partial.ipxe.contents.tmp
	fi

	cat \
		/tmp/partial.ipxe.header.tmp \
		/tmp/partial.ipxe.menu.tmp \
		/tmp/partial.ipxe.contents.tmp \
		> /srv/pxe/bootentries/menu.ipxe
	rm -f /tmp/partial.ipxe.*.tmp
	if [ "$entries_found" = "0" ]; then
		echo "Could not find any boot entries for PXE TFTP boot"
		return 1
	fi
	echo "Found $entries_found boot entries"
}

reload_service() {
	config_load bootentries
	config_foreach validate_bootentries_section bootentries bootentries_config
}

service_triggers() {
	procd_add_reload_trigger "bootentries"
	procd_add_validation validate_bootentries_section
}

start_service() {
	reload_service
}
