#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1


wait_for_lan_ipaddr() {
	. /lib/functions/network.sh
	echo "Waiting for LAN IP address..."
	for loop_idx in $(seq 1 5); do
		network_flush_cache
		network_get_ipaddr LAN_IPADDR lan
		if [ -n "${LAN_IPADDR}" ]; then
			echo "LAN IP address found."
			return 0
		fi
		sleep 5
	done
	echo "LAN IP address timeout."
	return 1
}

start_service() {

	if wait_for_lan_ipaddr; then
		echo -e "\nLAN IP address [DHCP]: ${LAN_IPADDR}" > /dev/console
		echo "LAN DHCP configuration complete, not falling back to static IP."
		return 0
	fi

	echo "LAN DHCP failed, falling back to static IP..."

	uci set network.lan.proto='static'
	uci set network.lan.ipaddr='192.168.200.1'	# TODO: get this from config
	uci commit network

	uci set dhcp.lan.proxy='0'
	uci delete dhcp.@dnsmasq[0].pxe_prompt
	uci delete dhcp.@dnsmasq[0].pxe_service
	uci commit dhcp

	/etc/init.d/network restart
	/etc/init.d/dnsmasq restart

	echo -e "\nLAN IP address [static]: $(uci get network.lan.ipaddr)" > /dev/console
}
