#!/bin/sh

# Provide easy access to some useful commands
# The 

uci -q batch << EOF
add luci command
set luci.@command[-1].name="iSCSI Target Status"
set luci.@command[-1].command="/etc/init.d/tgt show"

add luci command
set luci.@command[-1].name='Enable PXE File Access'
set luci.@command[-1].command='/etc/init.d/pxe_access start'

set luci.cmd_pxe_disable='command'
set luci.cmd_pxe_disable.name='Disable PXE File Access'
set luci.cmd_pxe_disable.command='/etc/init.d/pxe_access stop'
set luci.cmd_pxe_disable.public='1'

add luci command
set luci.@command[-1].name='Reload PXE menu'
set luci.@command[-1].command='/etc/init.d/pxe_menu reload'

add luci command
set luci.@command[-1].name='Linux iSCSI Initiator Script'
set luci.@command[-1].command='/srv/pxe/cgi-bin/iscsistart.sh'

add luci command
set luci.@command[-1].name='Windows iSCSI Initiator Script'
set luci.@command[-1].command='/srv/pxe/cgi-bin/iscsi-windows.ps1'

commit luci
EOF
