#!/bin/sh
set -e

# Add an extra HTTP server for the PXE files

cat > /etc/httpd.srv_pxe.conf <<EOF
/bootentries/:$(uci get bootentries.@bootentries[0].menu_username):$(uci get bootentries.@bootentries[0].menu_password)
/cgi-bin/:$(uci get bootentries.@bootentries[0].menu_username):$(uci get bootentries.@bootentries[0].menu_password)
EOF

uci -q batch << EOF
set uhttpd.srv_pxe='uhttpd'
set uhttpd.srv_pxe.home='/srv/pxe/'
add_list uhttpd.srv_pxe.listen_http='0.0.0.0:81'
add_list uhttpd.srv_pxe.listen_http='[::]:81'
set uhttpd.srv_pxe.config='/etc/httpd.srv_pxe.conf'
set uhttpd.srv_pxe.cgi_prefix='/cgi-bin'
set uhttpd.srv_pxe.script_timeout='60'
set uhttpd.srv_pxe.network_timeout='30'

commit uhttd
EOF