#!/bin/sh

# Configure dnsmasq for PXE TFTP boot.
#
# Limit DHCP assignments to 1 IP, to prevent accidental concurrent booting
# of multiple clients.

uci -q batch << EOF
set dhcp.@dnsmasq[0].local='/iscsi/'
set dhcp.@dnsmasq[0].domain='iscsi'
set dhcp.@dnsmasq[0].enable_tftp='1'
set dhcp.@dnsmasq[0].tftp_root='/srv/tftp'
set dhcp.@dnsmasq[0].dhcp_boot='pxelinux.0'
set dhcp.lan.start='2'
set dhcp.lan.limit='1'
set dhcp.lan.force='1'
commit dhcp
EOF
