#!/bin/sh

# Allow remote admin from WAN ports.

uci -q batch << EOF
add firewall rule
set firewall.@rule[-1].name='Allow-Remote-Admin'
set firewall.@rule[-1].enabled='true'
set firewall.@rule[-1].src='wan'
set firewall.@rule[-1].proto='tcp'
set firewall.@rule[-1].dest_port='22 80 443'
set firewall.@rule[-1].target='ACCEPT'
commit firewall
EOF
