#!/bin/sh
set -e

# Add an extra HTTP server for the PXE files

cat > /etc/httpd.srv_pxe.conf <<EOF
/bootentries/:$(uci get bootentries.@bootentries[0].menu_username):$(uci get bootentries.@bootentries[0].menu_password)
EOF

uci -q batch << EOF
set uhttpd.srv_pxe='uhttpd'
set uhttpd.srv_pxe.home='/srv/pxe/'
set uhttpd.srv_pxe.listen_http="$(uci get network.lan.ipaddr):81"
set uhttpd.srv_pxe.config='/etc/httpd.srv_pxe.conf'

commit uhttd
EOF